apiVersion: v1
appVersion: 0.0.1
description: Helm chart for deploying basic Spring applications
name: medium-customer
version: 0.0.1
maintainers:
  - name: torustad
    email: bard.torustad@gmail.com
