server:
  port: 10000
  tomcat:
    accesslog:
      enabled: true
      pattern: '%t %h %l %u \"%r\" %s %b zipkin:[%{X-B3-TraceId}i, %{X-B3-SpanId}i, %{X-B3-ParentSpanId}i]'
      directory: /home/baat/JAVA/SB-K8S-medium/customerlogs
      prefix: access_log
      suffix: .log
      buffered: false
spring:
  application:
    name: customer
  jackson:
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: false
  liquibase:
    change-log: "classpath:db/changelog/db.changelog-master.yaml"
springdoc:
  api-docs:
    enabled: true
    path: /api-docs
---
spring:
  profiles:
  - postgresdb
  datasource:
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 2
    url: jdbc:postgresql://localhost:5432/postgres
