apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-demo
spec:
  selector:
    matchLabels:
      app: postgres
  serviceName: "postgres"
  replicas: 2
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: pks-harbor.ad.forskningsradet.no/prosjekt0/postgresql:11.7.0-debian-10-r9
        envFrom:
          - configMapRef:
              name: postgres-config-demo
        ports:
        - containerPort: 5432
          name: postgresdb
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          subPath: postgres
          name: postgresdb
  volumeClaimTemplates:
  - metadata:
      name: postgresdb
    spec:
      accessModes: [ "ReadWriteOnce" ]
      # storageClassName: gp2
      resources:
        requests:
          storage: 3Gi
